## 1. Робота з NumPy 

In [73]:
# Використання arange
import numpy as np

# Генеруємо масив від 0 до 5 з кроком 1
a1 = np.arange(6)
print(a1)
print("\n")

# Генеруємо масив від 0 до 100 з кроком 20
my_array = np.arange(0, 101, 20)
print(my_array)

[0 1 2 3 4 5]


[  0  20  40  60  80 100]


In [74]:
# Створення масиву розміром 4x4 зі згенерованими випадковими цілими числами від 1 до 30
arr1 = np.random.randint(1, 10, (4, 4))
print("\n", arr1)

arr2 = np.random.randint(1, 10, (4, 4))
print("\n", arr2)

# Обчислення скалярного добутку
scalar = np.dot(arr1, arr2)
print("\nСкалярний добуток arr1 і arr2:", "\n", scalar)


 [[5 7 3 4]
 [8 3 3 1]
 [1 4 2 8]
 [4 3 2 5]]

 [[3 3 8 1]
 [2 3 3 3]
 [5 4 2 8]
 [6 3 4 3]]

Скалярний добуток arr1 і arr2: 
 [[68 60 83 62]
 [51 48 83 44]
 [69 47 56 53]
 [58 44 65 44]]


In [75]:
# Створення масиву розміром 4x4 зі згенерованими випадковими цілими числами від 1 до 30
arr3 = np.random.randint(1, 10, (5, 5))
print("Масив, з яким працюємо","\n", arr3)

# Отримуємо вектор з другого рядка (індекс 1)
vector2 = arr3[1, :]
print("\nВектор другого рядка:")
print(vector2)

# Отримуємо вектор з першого рядка
vector3 = arr3[0, :]
print("\nВектор першого рядка:")
print(vector3)

# Отримуємо вектор з четвертого рядка
vector3 = arr3[3, :]
print("\nВектор четвертого рядка:")
print(vector3)

Масив, з яким працюємо 
 [[5 1 3 4 5]
 [5 7 3 8 1]
 [5 6 1 1 1]
 [9 8 6 1 1]
 [2 9 6 2 1]]

Вектор другого рядка:
[5 7 3 8 1]

Вектор першого рядка:
[5 1 3 4 5]

Вектор четвертого рядка:
[9 8 6 1 1]


In [76]:
# Створення масиву
array = np.array([[1, 2], [3, 6]])
print("Масив\n", array, "\n")

# Створення матриць
matrix1 = np.matrix([[1, 2], [3, 4]])
print("Матриця 1:\n", matrix1, "\n")

matrix2 = np.matrix([[1, 1], [1, 1]])
print("Матриця 2:\n", matrix2)

# Дії над матрицями
# Додавання матриць
sum = matrix1 + matrix2
print("\nДодавання матриць:")
print(sum)

# Віднімання матриць
diff = matrix1 - matrix2
print("\nВіднімання матриць:")
print(diff)

# Множення матриць
prod = np.dot(matrix1, matrix2)
print("\nМноження матриць:")
print(prod)

# Транспонування матриці 1 (відображення по головній діпгоналі)
transposed1 = matrix1.T
print("\nТранспонування матриці 1:")
print(transposed1)

Масив
 [[1 2]
 [3 6]] 

Матриця 1:
 [[1 2]
 [3 4]] 

Матриця 2:
 [[1 1]
 [1 1]]

Додавання матриць:
[[2 3]
 [4 5]]

Віднімання матриць:
[[0 1]
 [2 3]]

Множення матриць:
[[3 3]
 [7 7]]

Транспонування матриці 1:
[[1 3]
 [2 4]]


## 2. Pandas (створити dataframe різними способами, провести маніпуляції з даними (head, describe, iloc, loc ...))

In [77]:
# Створення dataframe різними способами
import pandas as pd

# Створюємо DataFrame зі списку списків
data = [[14343656, 'Jay', 25, "Pilot"],
        [22336565, 'Linda', 22, "Teacher"],
        [32328333, 'Garu', 30, "Businessman"]]

columns = ['ID', 'Name', 'Age', 'Job']

df = pd.DataFrame(data, columns=columns)
print(df)
print('\n')


# Створюємо DataFrame зі словника
data2 = {'ID': [13469798, 58497584, 34896373],
        'Name': ['Jay', 'Linda', 'Garu'],
        'Age': [25, 22, 30],
        'Job': ['Pilot', 'Teacher', 'Businessman']}

df2 = pd.DataFrame(data2)
print(df2)
print('\n')

# Створюємо DataFrame зі списку словників
data3 = [{'ID': 14333245, 'Name': 'Jay', 'Age': 25, 'Job': 'Artist'},
        {'ID': 24347898, 'Name': 'Jack', 'Age': 22, 'Job': 'Producer'},
        {'ID': 33235679, 'Name': 'Tay', 'Age': 30, 'Job': 'Architector'}]

df3 = pd.DataFrame(data3)
print(df3)

         ID   Name  Age          Job
0  14343656    Jay   25        Pilot
1  22336565  Linda   22      Teacher
2  32328333   Garu   30  Businessman


         ID   Name  Age          Job
0  13469798    Jay   25        Pilot
1  58497584  Linda   22      Teacher
2  34896373   Garu   30  Businessman


         ID  Name  Age          Job
0  14333245   Jay   25       Artist
1  24347898  Jack   22     Producer
2  33235679   Tay   30  Architector


In [78]:
#  Mаніпуляції з даними (head, describe, iloc, loc ...))

print("Mаніпуляції з даними (head, describe, ...))\n")
print(df3)
print('\n')

# Вивід перших декількох рядків DataFrame
print("Перші 2 рядки:")
print(df3.head(2))

# Вивід описової статистики даних
print("\nОписова статистика:")
print(df3.describe())

# Вибірка окремих стовпців
ages = df3['Age']
print("\nСтовпець Age:")
print(ages)

Mаніпуляції з даними (head, describe, ...))

         ID  Name  Age          Job
0  14333245   Jay   25       Artist
1  24347898  Jack   22     Producer
2  33235679   Tay   30  Architector


Перші 2 рядки:
         ID  Name  Age       Job
0  14333245   Jay   25    Artist
1  24347898  Jack   22  Producer

Описова статистика:
                 ID        Age
count  3.000000e+00   3.000000
mean   2.397227e+07  25.666667
std    9.456814e+06   4.041452
min    1.433324e+07  22.000000
25%    1.934057e+07  23.500000
50%    2.434790e+07  25.000000
75%    2.879179e+07  27.500000
max    3.323568e+07  30.000000

Стовпець Age:
0    25
1    22
2    30
Name: Age, dtype: int64


In [79]:
# Продовження
print("Продовження:")
print("Mаніпуляції з даними (iloc, ...))")
print("Повний dataframe:\n")
print(df3)
print('\n')

# Фільтрація за умовою
young_people = df3[df3['Age'] < 30]
print("Молоді люди:")
print(young_people)
print('\n')

# Вибираємо дані за допомогою індексації
# Вибираємо рядок за індексом 2 (третій рядок)
row_3 = df3.iloc[2]

# Вибираємо елемент за індексами (рядок 4, стовпець 'Age')
age_of_row_4 = df3.iloc[2, df3.columns.get_loc('Age')]

print("Рядок за індексом 2:")
print(row_3)
print('\n')

print("Вік рядка за індексом 4:")
print(age_of_row_4)

Продовження:
Mаніпуляції з даними (iloc, ...))
Повний dataframe:

         ID  Name  Age          Job
0  14333245   Jay   25       Artist
1  24347898  Jack   22     Producer
2  33235679   Tay   30  Architector


Молоді люди:
         ID  Name  Age       Job
0  14333245   Jay   25    Artist
1  24347898  Jack   22  Producer


Рядок за індексом 2:
ID         33235679
Name            Tay
Age              30
Job     Architector
Name: 2, dtype: object


Вік рядка за індексом 4:
30


In [80]:
print("Mаніпуляції з даними (loc, ...))")
print('\n')
print("Весь dataframe для демонстрації loc:")

# Створюємо DataFrame з індексацією
data4 = {'Name': ['Dai', 'Meniya', 'Dave'],
        'Age': [50, 29, 38],
        'Work': ['Operator', 'Musician', 'Singer']}

df4 = pd.DataFrame(data4, index=['a', 'b', 'c'])
print(df4)
print('\n')

# Вибираємо дані за допомогою індексації
# Вибираємо рядок за міткою індексу 'b'
row_b = df4.loc['b']

# Вибираємо елемент за міткою індексу 'c' та назвою стовпця 'Work'
work_of_row_c = df4.loc['c', 'Work']
work_of_row_a = df4.loc['a', 'Work']
name_of_row_b = df4.loc['b', 'Name']
name_of_row_a = df4.loc['a', 'Name']
age_of_row_c = df4.loc['c', 'Age']

print("Рядок за індексом 'b': ")
print(row_b)

print("\nРобота рядка за індексом 'с': ", work_of_row_c)
print("\nРобота рядка за індексом 'a': ", work_of_row_a)
print("\nІм`я рядка за індексом 'b': ", name_of_row_b)
print("\nІм`я рядка за індексом 'a': ", name_of_row_a)
print("\nВік рядка за індексом 'c': ", age_of_row_c)

Mаніпуляції з даними (loc, ...))


Весь dataframe для демонстрації loc:
     Name  Age      Work
a     Dai   50  Operator
b  Meniya   29  Musician
c    Dave   38    Singer


Рядок за індексом 'b': 
Name      Meniya
Age           29
Work    Musician
Name: b, dtype: object

Робота рядка за індексом 'с':  Singer

Робота рядка за індексом 'a':  Operator

Ім`я рядка за індексом 'b':  Meniya

Ім`я рядка за індексом 'a':  Dai

Вік рядка за індексом 'c':  38


## Matplotlib

(створити набір даних лінійної функції з урахуванням помилок вимірювань, побудувати графік функції та згенерованих даних, обчислити похибку з використанням метрик MAE, MSE). Записати отримані результати у csv файл (формат: X,Y, Y_hat, mAE, mSE)