# Training to use NumPy library

In [27]:
#%pip install numpy
# import numpy as np

# Створення одновимірного масиву
# arr1 = np.array([1, 2, 3, 4, 5, 6])
# print("Одновимірний масив: ")
# print(arr1)

# Створення двовимірного масиву (матриця)
# arr2 = np.array([[2, 4, 6], [8, 10, 12], [14, 16, 18]])
# print("Двовимірний масив: ")
# print(arr2)

# Матоперації над масивами
# a1 = np.array([10, 20, 30])
# a2 = np.array([1, 2, 3])
# print("Масив a1:", a1)
# print("Масив a2:", a2)
# print("Додавання a1 + a2:", a1 + a2)
# print("Віднімання a - b:", a1 - a2)
# print("Множення a * b:", a1 * a2)
# print("Ділення a / b:", a1 / a2)

# Обчислення скалярного добутку
dot_product = np.dot(a1, a2)
print("\nСкалярний добуток a і b:", dot_product)

# Індексація та зрізи
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13])
print("Масив arr:", arr)
print("Елемент з індексом 13:", arr[13])
print("Зріз від 6 до 11 (не включаючи 11):", arr[6:11])
print("Кожен п'ятий елемент:", arr[::5])


Скалярний добуток a і b: 140
Масив arr: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13]
Елемент з індексом 13: 13
Зріз від 6 до 11 (не включаючи 11): [ 6  7  8  9 10]
Кожен п'ятий елемент: [ 0  5 10]


In [51]:
# Генерація масивів з використанням функцій NumPy
import numpy as np

# Створення масиву з нулів розміром 3x3
# zeros_array = np.zeros((3, 3))
# print(zeros_array)

# Створення масиву з одиниць розміром 2x4
# ones_array = np.ones((3, 4))
# print("\n", ones_array)

# Створення масиву розміром 3x3 зі згенерованими випадковими числами, від [0 до 1)
random_array = np.random.rand(3, 3)
print("\n", random_array)

# Створення масиву розміром 2x2 зі згенерованими випадковими цілими числами від 1 до 30
random_int_array = np.random.randint(1, 30, (2, 2))
print("\n", random_int_array)

# Створення послідовності чисел від 0 до 6
# sequence_array = np.arange(7)
# print("\n", sequence_array)

# Створення масиву розміром 5x5 з рівномірно розподіленими значеннями від 1 до 11; 9 - к-сть елементів, 3Х3 - розмір
uniform_array = np.linspace(1, 11, 9).reshape(3, 3)
print("\n", uniform_array)





 [[0.79769956 0.82375754 0.51854767]
 [0.50542881 0.32610984 0.46210142]
 [0.6077294  0.2825636  0.03684487]]

 [[25 18]
 [15 14]]

 [[ 1.    2.25  3.5 ]
 [ 4.75  6.    7.25]
 [ 8.5   9.75 11.  ]]
