# Training to use NumPy library

In [27]:
#%pip install numpy
# import numpy as np

# Створення одновимірного масиву
# arr1 = np.array([1, 2, 3, 4, 5, 6])
# print("Одновимірний масив: ")
# print(arr1)

# Створення двовимірного масиву (матриця)
# arr2 = np.array([[2, 4, 6], [8, 10, 12], [14, 16, 18]])
# print("Двовимірний масив: ")
# print(arr2)

# Матоперації над масивами
# a1 = np.array([10, 20, 30])
# a2 = np.array([1, 2, 3])
# print("Масив a1:", a1)
# print("Масив a2:", a2)
# print("Додавання a1 + a2:", a1 + a2)
# print("Віднімання a - b:", a1 - a2)
# print("Множення a * b:", a1 * a2)
# print("Ділення a / b:", a1 / a2)

# Обчислення скалярного добутку
dot_product = np.dot(a1, a2)
print("\nСкалярний добуток a і b:", dot_product)

# Індексація та зрізи
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13])
print("Масив arr:", arr)
print("Елемент з індексом 13:", arr[13])
print("Зріз від 6 до 11 (не включаючи 11):", arr[6:11])
print("Кожен п'ятий елемент:", arr[::5])


Скалярний добуток a і b: 140
Масив arr: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13]
Елемент з індексом 13: 13
Зріз від 6 до 11 (не включаючи 11): [ 6  7  8  9 10]
Кожен п'ятий елемент: [ 0  5 10]


In [51]:
# Генерація масивів з використанням функцій NumPy
import numpy as np

# Створення масиву з нулів розміром 3x3
# zeros_array = np.zeros((3, 3))
# print(zeros_array)

# Створення масиву з одиниць розміром 2x4
# ones_array = np.ones((3, 4))
# print("\n", ones_array)

# Створення масиву розміром 3x3 зі згенерованими випадковими числами, від [0 до 1)
random_array = np.random.rand(3, 3)
print("\n", random_array)

# Створення масиву розміром 2x2 зі згенерованими випадковими цілими числами від 1 до 30
random_int_array = np.random.randint(1, 30, (2, 2))
print("\n", random_int_array)

# Створення послідовності чисел від 0 до 6
# sequence_array = np.arange(7)
# print("\n", sequence_array)

# Створення масиву розміром 5x5 з рівномірно розподіленими значеннями від 1 до 11; 9 - к-сть елементів, 3Х3 - розмір
uniform_array = np.linspace(1, 11, 9).reshape(3, 3)
print("\n", uniform_array)





 [[0.79769956 0.82375754 0.51854767]
 [0.50542881 0.32610984 0.46210142]
 [0.6077294  0.2825636  0.03684487]]

 [[25 18]
 [15 14]]

 [[ 1.    2.25  3.5 ]
 [ 4.75  6.    7.25]
 [ 8.5   9.75 11.  ]]


# Початок виконання Практики2

Підключення необхідних бібліотек

In [61]:
# Імпортуємо необхідні бібліотеки:  
import numpy as np                   # NumPy для роботи з числовими даними
import pandas as pd                  # Pandas для обробки і аналізу даних
import matplotlib.pyplot as plt      # Matplotlib для візуалізації результатів

In [65]:
# # Генерація випадкових даних
# np.random.seed(0)  # Щоб мати однакові результати при кожному запуску
# num_samples = 100  # Кількість рядків (зразків)
# num_features = 4  # Кількість ознак

# # Генерація випадкових ознак і цільової змінної
# data = np.random.rand(num_samples, num_features)  # Останній стовпець - це цільова змінна
# columns = ['First_feature', 'Second_Feature', 'Third_Feature', 'Target(y)']
# df = pd.DataFrame(data, columns=columns)          # створення таблиці з переданими стовпцями та інформацією

# # Збереження даних у файл CSV
# df.to_csv('випадкові_дані.csv', index=False)

Генерація випадкових даних (перші 3 стовпчики - дані кредитних заявок, 4й - 1/0 - прийнято/не прийнято заявку)

In [82]:
# Генерація випадкових даних
np.random.seed(0)  # Щоб мати однакові результати при кожному запуску
num_samples = 100  # Кількість рядків (зразків)
num_features = 3  # Кількість ознак
num_cat_features = 1  # Кількість категорійних ознак
categories = [0, 1]  # Можливі категорії
columns = ['Feature 1', 'Feature 2', 'Feature 3', 'Category(y/n)']

# Генерація випадкових ознак
data = np.random.rand(num_samples, num_features)  # генеруємо дані
cat_features = np.random.choice(categories, size=(num_samples, num_cat_features))   # Генеруємо категорії

all_data = np.hstack((data, cat_features))  # Об'єднуємо числові та категорійні ознаки, як матрицю ознак X 

df = pd.DataFrame(all_data, columns=columns)   # створення таблиці з переданими стовпцями та інформацією
df.to_csv('випадкові_дані.csv', index=False)   # Збереження даних у файл CSV

Вивід даних у зручній формі за допомогою Pandas

In [93]:
# Завантаження даних за допомогою Pandas
data = pd.read_csv('випадкові_дані.csv')

# Перегляд перших декількох рядків даних
print("---Перегляд перших декількох рядків даних---")
print(data.head(), "\n")

# Вивести інформацію про дані, такі як кількість рядків, стовпців і типи даних
print("---Вивід інформації про дані: к-сті рядків, стовпців, типу даних---")
print(data.info(), "\n")

# Вивести основні статистичні показники даних
print("---Основні статистичні показники даних---")
print(data.describe(), "\n")

---Перегляд перших декількох рядків даних---
   Feature 1  Feature 2  Feature 3  Category
0   0.548814   0.715189   0.602763       0.0
1   0.544883   0.423655   0.645894       0.0
2   0.437587   0.891773   0.963663       1.0
3   0.383442   0.791725   0.528895       1.0
4   0.568045   0.925597   0.071036       1.0 

---Вивід інформації про дані: к-сті рядків, стовпців, типу даних---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   Feature 1  100 non-null    float64
 1   Feature 2  100 non-null    float64
 2   Feature 3  100 non-null    float64
 3   Category   100 non-null    float64
dtypes: float64(4)
memory usage: 3.2 KB
None 

---Основні статистичні показники даних---
        Feature 1   Feature 2   Feature 3    Category
count  100.000000  100.000000  100.000000  100.000000
mean     0.501680    0.486570    0.522258    0.530000
std      0.297925    

Підготовка даних (обробка пропущених, вибір функції для аналізу, розділення даних)